version: '3.4'

networks:
  eshop-dev:
    driver: bridge 

services:
  eshop:
    image: eshop:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      # DB_CONNECTION_STRING: "Host=postgres_image; port=5432; Database=eshop; Username=postgres; Password=postgres"
      DB_HOST: postgres_image
      DB_PORT: 5432
      DB_DATABASE: eshop
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - eshop-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      # - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "eshop"
    networks:
      - eshop-dev
volumes:
  db_volume: