FROM webdevops/php-nginx:8.2-alpine
ENV WEB_DOCUMENT_ROOT=/app/public
ENV PHP_DISMOD=bz2,calendar,exiif,ffi,intl,gettext,ldap,mysqli,imap,pdo_pgsql,pgsql,soap,sockets,sysvmsg,sysvsm,sysvshm,shmop,xsl,zip,gd,apcu,vips,yaml,imagick,mongodb,amqp
WORKDIR /app
# COPY composer.json composer.json
# COPY composer.lock composer.lock
COPY composer.lock composer.json
RUN ls
RUN composer install --no-interaction --optimize-autoloader --no-dev
COPY . .
RUN php artisan migrate
RUN php artisan db:seed --class="CategorySeeder"
RUN php artisan db:seed --class="ProductSeeder"
# RUN php artisan db:seed --class="DatabaseSeeder"
# Ensure all of our files are owned by the same user and group.
RUN chown -R application:application .
ENTRYPOINT ["php artisan serve"]